/**
 * GENERATED FILE. Exhaustive, type-safe Firestore path helpers.
 * This is not a substitute for authorization or runtime validation.
 * Run `npm run generate:contracts` after changing the authoritative schema.
 */

export const documentPatterns = {
  SchemaVersionDocument: "_schema/{version}",
  AppConfigDocument: "appConfig/{configId}",
  FeatureFlagDocument: "featureFlags/{flagId}",
  SupportedLocaleDocument: "supportedLocales/{localeCode}",
  GovernmentServiceDocument: "governmentServices/{serviceId}",
  EmergencyPhrasebookDocument: "emergencyPhrasebooks/{phrasebookId}",
  EmergencyPhraseDocument: "emergencyPhrasebooks/{phrasebookId}/phrases/{phraseId}",
  TerminologyGlossaryDocument: "terminologyGlossaries/{glossaryId}",
  TerminologyEntryDocument: "terminologyGlossaries/{glossaryId}/entries/{entryId}",
  KnowledgeArticleDocument: "knowledgeArticles/{articleId}",
  TrainingModuleDocument: "trainingModules/{moduleId}",
  TrainingLessonDocument: "trainingModules/{moduleId}/lessons/{lessonId}",
  SafetyRuleSetDocument: "safetyRuleSets/{ruleSetId}",
  SafetyRuleDocument: "safetyRuleSets/{ruleSetId}/rules/{ruleId}",
  PromptTemplateDocument: "promptTemplates/{templateId}",
  ModelPolicyDocument: "modelPolicies/{policyId}",
  OrganizationDocument: "organizations/{organizationId}",
  OrganizationMemberDocument: "organizations/{organizationId}/members/{uid}",
  OrganizationSiteDocument: "organizations/{organizationId}/sites/{siteId}",
  UserDocument: "users/{uid}",
  UserDeviceDocument: "users/{uid}/devices/{deviceId}",
  UserPreferenceDocument: "users/{uid}/preferences/{preferenceId}",
  UserNotificationDocument: "users/{uid}/notifications/{notificationId}",
  TrainingProgressDocument: "users/{uid}/trainingProgress/{moduleId}",
  WellbeingCheckInDocument: "users/{uid}/wellbeingCheckIns/{checkInId}",
  PrivateSupportRequestDocument: "users/{uid}/privateSupportRequests/{requestId}",
  PrivateSupportMessageDocument: "users/{uid}/privateSupportRequests/{requestId}/messages/{messageId}",
  PrivateSupportReferralDocument: "users/{uid}/privateSupportRequests/{requestId}/referrals/{referralId}",
  PrivateMediaAssetDocument: "users/{uid}/privateMediaAssets/{assetId}",
  ConsentRecordDocument: "users/{uid}/consents/{consentId}",
  DataSubjectRequestDocument: "users/{uid}/dataSubjectRequests/{requestId}",
  EmergencySessionDocument: "users/{uid}/emergencySessions/{sessionId}",
  HouseholdDocument: "households/{householdId}",
  HouseholdMemberDocument: "households/{householdId}/members/{uid}",
  HouseholdInvitationDocument: "households/{householdId}/invitations/{invitationId}",
  HouseholdSettingDocument: "households/{householdId}/settings/{settingsId}",
  HouseholdOrganizationLinkDocument: "households/{householdId}/organizationLinks/{linkId}",
  AccessGrantDocument: "households/{householdId}/accessGrants/{grantId}",
  CareThreadDocument: "households/{householdId}/threads/{threadId}",
  CareThreadMessageDocument: "households/{householdId}/threads/{threadId}/messages/{messageId}",
  ServiceReferralDocument: "households/{householdId}/serviceReferrals/{referralId}",
  HouseholdMediaAssetDocument: "households/{householdId}/mediaAssets/{assetId}",
  CareRecipientDocument: "households/{householdId}/careRecipients/{careRecipientId}",
  CareAssignmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/assignments/{caregiverUid}",
  CarePlanDocument: "households/{householdId}/careRecipients/{careRecipientId}/carePlans/{carePlanId}",
  ObservationDocument: "households/{householdId}/careRecipients/{careRecipientId}/observations/{observationId}",
  InstructionDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions/{instructionId}",
  InstructionStepDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions/{instructionId}/steps/{stepId}",
  InstructionConfirmationDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions/{instructionId}/confirmations/{confirmationId}",
  CareTaskDocument: "households/{householdId}/careRecipients/{careRecipientId}/tasks/{taskId}",
  CareTaskEventDocument: "households/{householdId}/careRecipients/{careRecipientId}/taskEvents/{taskEventId}",
  MedicationDocument: "households/{householdId}/careRecipients/{careRecipientId}/medications/{medicationId}",
  MedicationEventDocument: "households/{householdId}/careRecipients/{careRecipientId}/medicationEvents/{eventId}",
  MeasurementDocument: "households/{householdId}/careRecipients/{careRecipientId}/measurements/{measurementId}",
  IncidentDocument: "households/{householdId}/careRecipients/{careRecipientId}/incidents/{incidentId}",
  CareHandoverDocument: "households/{householdId}/careRecipients/{careRecipientId}/handovers/{handoverId}",
  AppointmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/appointments/{appointmentId}",
  CareRecipientAttachmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/documents/{documentId}",
  CareReportDocument: "households/{householdId}/careRecipients/{careRecipientId}/reports/{reportId}",
  AlertDocument: "households/{householdId}/careRecipients/{careRecipientId}/alerts/{alertId}",
  SymptomCheckDocument: "households/{householdId}/careRecipients/{careRecipientId}/symptomChecks/{symptomCheckId}",
  DailySummaryDocument: "households/{householdId}/careRecipients/{careRecipientId}/dailySummaries/{dateKey}",
  WeeklySummaryDocument: "households/{householdId}/careRecipients/{careRecipientId}/weeklySummaries/{weekKey}",
  ProcessingJobDocument: "processingJobs/{jobId}",
  AiRunDocument: "aiRuns/{runId}",
  NotificationOutboxDocument: "notificationOutbox/{messageId}",
  IdempotencyKeyDocument: "idempotencyKeys/{keyHash}",
  AuditEventDocument: "auditEvents/{auditId}",
  ScheduledWorkDocument: "scheduledWork/{workId}",
  MigrationDocument: "migrations/{migrationId}",
  PilotStudyDocument: "pilotStudies/{studyId}",
  PilotStudySiteDocument: "pilotStudies/{studyId}/sites/{siteId}",
  PilotParticipantDocument: "pilotStudies/{studyId}/participants/{participantId}",
  PilotSessionDocument: "pilotStudies/{studyId}/sessions/{sessionId}",
  PilotFeedbackDocument: "pilotStudies/{studyId}/feedback/{feedbackId}",
  PilotMetricSnapshotDocument: "pilotStudies/{studyId}/metricSnapshots/{snapshotId}",
} as const;

export const collectionPatterns = {
  SchemaVersionDocument: "_schema",
  AppConfigDocument: "appConfig",
  FeatureFlagDocument: "featureFlags",
  SupportedLocaleDocument: "supportedLocales",
  GovernmentServiceDocument: "governmentServices",
  EmergencyPhrasebookDocument: "emergencyPhrasebooks",
  EmergencyPhraseDocument: "emergencyPhrasebooks/{phrasebookId}/phrases",
  TerminologyGlossaryDocument: "terminologyGlossaries",
  TerminologyEntryDocument: "terminologyGlossaries/{glossaryId}/entries",
  KnowledgeArticleDocument: "knowledgeArticles",
  TrainingModuleDocument: "trainingModules",
  TrainingLessonDocument: "trainingModules/{moduleId}/lessons",
  SafetyRuleSetDocument: "safetyRuleSets",
  SafetyRuleDocument: "safetyRuleSets/{ruleSetId}/rules",
  PromptTemplateDocument: "promptTemplates",
  ModelPolicyDocument: "modelPolicies",
  OrganizationDocument: "organizations",
  OrganizationMemberDocument: "organizations/{organizationId}/members",
  OrganizationSiteDocument: "organizations/{organizationId}/sites",
  UserDocument: "users",
  UserDeviceDocument: "users/{uid}/devices",
  UserPreferenceDocument: "users/{uid}/preferences",
  UserNotificationDocument: "users/{uid}/notifications",
  TrainingProgressDocument: "users/{uid}/trainingProgress",
  WellbeingCheckInDocument: "users/{uid}/wellbeingCheckIns",
  PrivateSupportRequestDocument: "users/{uid}/privateSupportRequests",
  PrivateSupportMessageDocument: "users/{uid}/privateSupportRequests/{requestId}/messages",
  PrivateSupportReferralDocument: "users/{uid}/privateSupportRequests/{requestId}/referrals",
  PrivateMediaAssetDocument: "users/{uid}/privateMediaAssets",
  ConsentRecordDocument: "users/{uid}/consents",
  DataSubjectRequestDocument: "users/{uid}/dataSubjectRequests",
  EmergencySessionDocument: "users/{uid}/emergencySessions",
  HouseholdDocument: "households",
  HouseholdMemberDocument: "households/{householdId}/members",
  HouseholdInvitationDocument: "households/{householdId}/invitations",
  HouseholdSettingDocument: "households/{householdId}/settings",
  HouseholdOrganizationLinkDocument: "households/{householdId}/organizationLinks",
  AccessGrantDocument: "households/{householdId}/accessGrants",
  CareThreadDocument: "households/{householdId}/threads",
  CareThreadMessageDocument: "households/{householdId}/threads/{threadId}/messages",
  ServiceReferralDocument: "households/{householdId}/serviceReferrals",
  HouseholdMediaAssetDocument: "households/{householdId}/mediaAssets",
  CareRecipientDocument: "households/{householdId}/careRecipients",
  CareAssignmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/assignments",
  CarePlanDocument: "households/{householdId}/careRecipients/{careRecipientId}/carePlans",
  ObservationDocument: "households/{householdId}/careRecipients/{careRecipientId}/observations",
  InstructionDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions",
  InstructionStepDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions/{instructionId}/steps",
  InstructionConfirmationDocument: "households/{householdId}/careRecipients/{careRecipientId}/instructions/{instructionId}/confirmations",
  CareTaskDocument: "households/{householdId}/careRecipients/{careRecipientId}/tasks",
  CareTaskEventDocument: "households/{householdId}/careRecipients/{careRecipientId}/taskEvents",
  MedicationDocument: "households/{householdId}/careRecipients/{careRecipientId}/medications",
  MedicationEventDocument: "households/{householdId}/careRecipients/{careRecipientId}/medicationEvents",
  MeasurementDocument: "households/{householdId}/careRecipients/{careRecipientId}/measurements",
  IncidentDocument: "households/{householdId}/careRecipients/{careRecipientId}/incidents",
  CareHandoverDocument: "households/{householdId}/careRecipients/{careRecipientId}/handovers",
  AppointmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/appointments",
  CareRecipientAttachmentDocument: "households/{householdId}/careRecipients/{careRecipientId}/documents",
  CareReportDocument: "households/{householdId}/careRecipients/{careRecipientId}/reports",
  AlertDocument: "households/{householdId}/careRecipients/{careRecipientId}/alerts",
  SymptomCheckDocument: "households/{householdId}/careRecipients/{careRecipientId}/symptomChecks",
  DailySummaryDocument: "households/{householdId}/careRecipients/{careRecipientId}/dailySummaries",
  WeeklySummaryDocument: "households/{householdId}/careRecipients/{careRecipientId}/weeklySummaries",
  ProcessingJobDocument: "processingJobs",
  AiRunDocument: "aiRuns",
  NotificationOutboxDocument: "notificationOutbox",
  IdempotencyKeyDocument: "idempotencyKeys",
  AuditEventDocument: "auditEvents",
  ScheduledWorkDocument: "scheduledWork",
  MigrationDocument: "migrations",
  PilotStudyDocument: "pilotStudies",
  PilotStudySiteDocument: "pilotStudies/{studyId}/sites",
  PilotParticipantDocument: "pilotStudies/{studyId}/participants",
  PilotSessionDocument: "pilotStudies/{studyId}/sessions",
  PilotFeedbackDocument: "pilotStudies/{studyId}/feedback",
  PilotMetricSnapshotDocument: "pilotStudies/{studyId}/metricSnapshots",
} as const;

const canonicalPaths = {
  schemaVersion: (version: string) => `_schema/${version}`,
  schemaVersions: () => `_schema`,
  appConfig: (configId: string) => `appConfig/${configId}`,
  appConfigs: () => `appConfig`,
  featureFlag: (flagId: string) => `featureFlags/${flagId}`,
  featureFlags: () => `featureFlags`,
  supportedLocale: (localeCode: string) => `supportedLocales/${localeCode}`,
  supportedLocales: () => `supportedLocales`,
  governmentService: (serviceId: string) => `governmentServices/${serviceId}`,
  governmentServices: () => `governmentServices`,
  emergencyPhrasebook: (phrasebookId: string) => `emergencyPhrasebooks/${phrasebookId}`,
  emergencyPhrasebooks: () => `emergencyPhrasebooks`,
  emergencyPhrase: (phrasebookId: string, phraseId: string) => `emergencyPhrasebooks/${phrasebookId}/phrases/${phraseId}`,
  emergencyPhrases: (phrasebookId: string) => `emergencyPhrasebooks/${phrasebookId}/phrases`,
  terminologyGlossary: (glossaryId: string) => `terminologyGlossaries/${glossaryId}`,
  terminologyGlossaries: () => `terminologyGlossaries`,
  terminologyEntry: (glossaryId: string, entryId: string) => `terminologyGlossaries/${glossaryId}/entries/${entryId}`,
  terminologyEntries: (glossaryId: string) => `terminologyGlossaries/${glossaryId}/entries`,
  knowledgeArticle: (articleId: string) => `knowledgeArticles/${articleId}`,
  knowledgeArticles: () => `knowledgeArticles`,
  trainingModule: (moduleId: string) => `trainingModules/${moduleId}`,
  trainingModules: () => `trainingModules`,
  trainingLesson: (moduleId: string, lessonId: string) => `trainingModules/${moduleId}/lessons/${lessonId}`,
  trainingLessons: (moduleId: string) => `trainingModules/${moduleId}/lessons`,
  safetyRuleSet: (ruleSetId: string) => `safetyRuleSets/${ruleSetId}`,
  safetyRuleSets: () => `safetyRuleSets`,
  safetyRule: (ruleSetId: string, ruleId: string) => `safetyRuleSets/${ruleSetId}/rules/${ruleId}`,
  safetyRules: (ruleSetId: string) => `safetyRuleSets/${ruleSetId}/rules`,
  promptTemplate: (templateId: string) => `promptTemplates/${templateId}`,
  promptTemplates: () => `promptTemplates`,
  modelPolicy: (policyId: string) => `modelPolicies/${policyId}`,
  modelPolicies: () => `modelPolicies`,
  organization: (organizationId: string) => `organizations/${organizationId}`,
  organizations: () => `organizations`,
  organizationMember: (organizationId: string, uid: string) => `organizations/${organizationId}/members/${uid}`,
  organizationMembers: (organizationId: string) => `organizations/${organizationId}/members`,
  organizationSite: (organizationId: string, siteId: string) => `organizations/${organizationId}/sites/${siteId}`,
  organizationSites: (organizationId: string) => `organizations/${organizationId}/sites`,
  user: (uid: string) => `users/${uid}`,
  users: () => `users`,
  userDevice: (uid: string, deviceId: string) => `users/${uid}/devices/${deviceId}`,
  userDevices: (uid: string) => `users/${uid}/devices`,
  userPreference: (uid: string, preferenceId: string) => `users/${uid}/preferences/${preferenceId}`,
  userPreferences: (uid: string) => `users/${uid}/preferences`,
  userNotification: (uid: string, notificationId: string) => `users/${uid}/notifications/${notificationId}`,
  userNotifications: (uid: string) => `users/${uid}/notifications`,
  trainingProgress: (uid: string, moduleId: string) => `users/${uid}/trainingProgress/${moduleId}`,
  userTrainingProgress: (uid: string) => `users/${uid}/trainingProgress`,
  wellbeingCheckIn: (uid: string, checkInId: string) => `users/${uid}/wellbeingCheckIns/${checkInId}`,
  wellbeingCheckIns: (uid: string) => `users/${uid}/wellbeingCheckIns`,
  privateSupportRequest: (uid: string, requestId: string) => `users/${uid}/privateSupportRequests/${requestId}`,
  privateSupportRequests: (uid: string) => `users/${uid}/privateSupportRequests`,
  privateSupportMessage: (uid: string, requestId: string, messageId: string) => `users/${uid}/privateSupportRequests/${requestId}/messages/${messageId}`,
  privateSupportMessages: (uid: string, requestId: string) => `users/${uid}/privateSupportRequests/${requestId}/messages`,
  privateSupportReferral: (uid: string, requestId: string, referralId: string) => `users/${uid}/privateSupportRequests/${requestId}/referrals/${referralId}`,
  privateSupportReferrals: (uid: string, requestId: string) => `users/${uid}/privateSupportRequests/${requestId}/referrals`,
  privateMediaAsset: (uid: string, assetId: string) => `users/${uid}/privateMediaAssets/${assetId}`,
  privateMediaAssets: (uid: string) => `users/${uid}/privateMediaAssets`,
  userConsent: (uid: string, consentId: string) => `users/${uid}/consents/${consentId}`,
  userConsents: (uid: string) => `users/${uid}/consents`,
  dataSubjectRequest: (uid: string, requestId: string) => `users/${uid}/dataSubjectRequests/${requestId}`,
  dataSubjectRequests: (uid: string) => `users/${uid}/dataSubjectRequests`,
  userEmergencySession: (uid: string, sessionId: string) => `users/${uid}/emergencySessions/${sessionId}`,
  userEmergencySessions: (uid: string) => `users/${uid}/emergencySessions`,
  household: (householdId: string) => `households/${householdId}`,
  households: () => `households`,
  householdMember: (householdId: string, uid: string) => `households/${householdId}/members/${uid}`,
  householdMembers: (householdId: string) => `households/${householdId}/members`,
  householdInvitation: (householdId: string, invitationId: string) => `households/${householdId}/invitations/${invitationId}`,
  householdInvitations: (householdId: string) => `households/${householdId}/invitations`,
  householdSetting: (householdId: string, settingsId: string) => `households/${householdId}/settings/${settingsId}`,
  householdSettings: (householdId: string) => `households/${householdId}/settings`,
  householdOrganizationLink: (householdId: string, linkId: string) => `households/${householdId}/organizationLinks/${linkId}`,
  householdOrganizationLinks: (householdId: string) => `households/${householdId}/organizationLinks`,
  accessGrant: (householdId: string, grantId: string) => `households/${householdId}/accessGrants/${grantId}`,
  accessGrants: (householdId: string) => `households/${householdId}/accessGrants`,
  careThread: (householdId: string, threadId: string) => `households/${householdId}/threads/${threadId}`,
  careThreads: (householdId: string) => `households/${householdId}/threads`,
  careThreadMessage: (householdId: string, threadId: string, messageId: string) => `households/${householdId}/threads/${threadId}/messages/${messageId}`,
  careThreadMessages: (householdId: string, threadId: string) => `households/${householdId}/threads/${threadId}/messages`,
  serviceReferral: (householdId: string, referralId: string) => `households/${householdId}/serviceReferrals/${referralId}`,
  serviceReferrals: (householdId: string) => `households/${householdId}/serviceReferrals`,
  householdMediaAsset: (householdId: string, assetId: string) => `households/${householdId}/mediaAssets/${assetId}`,
  householdMediaAssets: (householdId: string) => `households/${householdId}/mediaAssets`,
  careRecipient: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}`,
  careRecipients: (householdId: string) => `households/${householdId}/careRecipients`,
  assignment: (householdId: string, careRecipientId: string, caregiverUid: string) => `households/${householdId}/careRecipients/${careRecipientId}/assignments/${caregiverUid}`,
  assignments: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/assignments`,
  carePlan: (householdId: string, careRecipientId: string, carePlanId: string) => `households/${householdId}/careRecipients/${careRecipientId}/carePlans/${carePlanId}`,
  carePlans: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/carePlans`,
  observation: (householdId: string, careRecipientId: string, observationId: string) => `households/${householdId}/careRecipients/${careRecipientId}/observations/${observationId}`,
  observations: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/observations`,
  instruction: (householdId: string, careRecipientId: string, instructionId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions/${instructionId}`,
  instructions: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions`,
  instructionStep: (householdId: string, careRecipientId: string, instructionId: string, stepId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions/${instructionId}/steps/${stepId}`,
  instructionSteps: (householdId: string, careRecipientId: string, instructionId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions/${instructionId}/steps`,
  instructionConfirmation: (householdId: string, careRecipientId: string, instructionId: string, confirmationId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions/${instructionId}/confirmations/${confirmationId}`,
  instructionConfirmations: (householdId: string, careRecipientId: string, instructionId: string) => `households/${householdId}/careRecipients/${careRecipientId}/instructions/${instructionId}/confirmations`,
  task: (householdId: string, careRecipientId: string, taskId: string) => `households/${householdId}/careRecipients/${careRecipientId}/tasks/${taskId}`,
  tasks: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/tasks`,
  taskEvent: (householdId: string, careRecipientId: string, taskEventId: string) => `households/${householdId}/careRecipients/${careRecipientId}/taskEvents/${taskEventId}`,
  taskEvents: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/taskEvents`,
  medication: (householdId: string, careRecipientId: string, medicationId: string) => `households/${householdId}/careRecipients/${careRecipientId}/medications/${medicationId}`,
  medications: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/medications`,
  medicationEvent: (householdId: string, careRecipientId: string, eventId: string) => `households/${householdId}/careRecipients/${careRecipientId}/medicationEvents/${eventId}`,
  medicationEvents: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/medicationEvents`,
  measurement: (householdId: string, careRecipientId: string, measurementId: string) => `households/${householdId}/careRecipients/${careRecipientId}/measurements/${measurementId}`,
  measurements: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/measurements`,
  incident: (householdId: string, careRecipientId: string, incidentId: string) => `households/${householdId}/careRecipients/${careRecipientId}/incidents/${incidentId}`,
  incidents: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/incidents`,
  handover: (householdId: string, careRecipientId: string, handoverId: string) => `households/${householdId}/careRecipients/${careRecipientId}/handovers/${handoverId}`,
  handovers: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/handovers`,
  appointment: (householdId: string, careRecipientId: string, appointmentId: string) => `households/${householdId}/careRecipients/${careRecipientId}/appointments/${appointmentId}`,
  appointments: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/appointments`,
  careRecipientAttachment: (householdId: string, careRecipientId: string, documentId: string) => `households/${householdId}/careRecipients/${careRecipientId}/documents/${documentId}`,
  careRecipientAttachments: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/documents`,
  report: (householdId: string, careRecipientId: string, reportId: string) => `households/${householdId}/careRecipients/${careRecipientId}/reports/${reportId}`,
  reports: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/reports`,
  alert: (householdId: string, careRecipientId: string, alertId: string) => `households/${householdId}/careRecipients/${careRecipientId}/alerts/${alertId}`,
  alerts: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/alerts`,
  symptomCheck: (householdId: string, careRecipientId: string, symptomCheckId: string) => `households/${householdId}/careRecipients/${careRecipientId}/symptomChecks/${symptomCheckId}`,
  symptomChecks: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/symptomChecks`,
  dailySummary: (householdId: string, careRecipientId: string, dateKey: string) => `households/${householdId}/careRecipients/${careRecipientId}/dailySummaries/${dateKey}`,
  dailySummaries: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/dailySummaries`,
  weeklySummary: (householdId: string, careRecipientId: string, weekKey: string) => `households/${householdId}/careRecipients/${careRecipientId}/weeklySummaries/${weekKey}`,
  weeklySummaries: (householdId: string, careRecipientId: string) => `households/${householdId}/careRecipients/${careRecipientId}/weeklySummaries`,
  processingJob: (jobId: string) => `processingJobs/${jobId}`,
  processingJobs: () => `processingJobs`,
  aiRun: (runId: string) => `aiRuns/${runId}`,
  aiRuns: () => `aiRuns`,
  notificationOutboxMessage: (messageId: string) => `notificationOutbox/${messageId}`,
  notificationOutbox: () => `notificationOutbox`,
  idempotencyKey: (keyHash: string) => `idempotencyKeys/${keyHash}`,
  idempotencyKeys: () => `idempotencyKeys`,
  auditEvent: (auditId: string) => `auditEvents/${auditId}`,
  auditEvents: () => `auditEvents`,
  scheduledWorkItem: (workId: string) => `scheduledWork/${workId}`,
  scheduledWork: () => `scheduledWork`,
  migration: (migrationId: string) => `migrations/${migrationId}`,
  migrations: () => `migrations`,
  pilotStudy: (studyId: string) => `pilotStudies/${studyId}`,
  pilotStudies: () => `pilotStudies`,
  pilotStudySite: (studyId: string, siteId: string) => `pilotStudies/${studyId}/sites/${siteId}`,
  pilotStudySites: (studyId: string) => `pilotStudies/${studyId}/sites`,
  pilotParticipant: (studyId: string, participantId: string) => `pilotStudies/${studyId}/participants/${participantId}`,
  pilotParticipants: (studyId: string) => `pilotStudies/${studyId}/participants`,
  pilotSession: (studyId: string, sessionId: string) => `pilotStudies/${studyId}/sessions/${sessionId}`,
  pilotSessions: (studyId: string) => `pilotStudies/${studyId}/sessions`,
  pilotFeedbackEntry: (studyId: string, feedbackId: string) => `pilotStudies/${studyId}/feedback/${feedbackId}`,
  pilotFeedback: (studyId: string) => `pilotStudies/${studyId}/feedback`,
  pilotMetricSnapshot: (studyId: string, snapshotId: string) => `pilotStudies/${studyId}/metricSnapshots/${snapshotId}`,
  pilotMetricSnapshots: (studyId: string) => `pilotStudies/${studyId}/metricSnapshots`,
} as const;

export const paths = {
  ...canonicalPaths,
  careAssignment: canonicalPaths.assignment,
  careAssignments: canonicalPaths.assignments,
  careTask: canonicalPaths.task,
  careTasks: canonicalPaths.tasks,
  careTaskEvent: canonicalPaths.taskEvent,
  careTaskEvents: canonicalPaths.taskEvents,
  careReport: canonicalPaths.report,
  careReports: canonicalPaths.reports,
} as const;

export type PathHelperName = keyof typeof paths;
export type FirestoreDocumentPattern = typeof documentPatterns[keyof typeof documentPatterns];
export type FirestoreCollectionPattern = typeof collectionPatterns[keyof typeof collectionPatterns];

