// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAuyVwW4kbO5HbOj1c4hUKdkp8xRhJes',
    appId: '1:742210340367:android:34817342e86c01bff0c57a',
    messagingSenderId: '742210340367',
    projectId: 'kalinga-bc97f',
    storageBucket: 'kalinga-bc97f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnr4nTxnjQTrS2bJBR5jTodgZrkOBqtY',
    appId: '1:742210340367:web:2616538a2a2bca6af0c57a',
    messagingSenderId: '742210340367',
    projectId: 'kalinga-bc97f',
    authDomain: 'kalinga-bc97f.firebaseapp.com',
    storageBucket: 'kalinga-bc97f.firebasestorage.app',
    measurementId: 'G-VKX5YY3PJS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnr4nTxnjQTrS2bJBR5jTodgZrkOBqtY',
    appId: '1:742210340367:web:2616538a2a2bca6af0c57a',
    messagingSenderId: '742210340367',
    projectId: 'kalinga-bc97f',
    authDomain: 'kalinga-bc97f.firebaseapp.com',
    storageBucket: 'kalinga-bc97f.firebasestorage.app',
    measurementId: 'G-VKX5YY3PJS',
  );
}
